schema = 1
project = "daukle/example-cmake-c-executable"
version = "1.0.0"

[modules]

[resolvers.github]
url = "https://raw.githubusercontent.com/daukle/daukle/f9055f9a07011283009675f4ffbc0a9b783c50bd/plugins/github-releases.lua"
sha256 = "3789865c266eb53fafcf7300d77a24461170c615195d92d0ddf88078c556e23e"

[plugins]
cmake = { resolver = "github", coordinate = "daukle/cmake@^1.0.0" }

[toolchains.cmake]
version = "4.4"
standard = 17
