schema = 1
project = "daukle/example-cmake-c-executable"
version = "1.0.0"

[modules]

[resolvers.github]
url = "https://raw.githubusercontent.com/daukle/daukle/23aa207d064bc2ed3e6fb30937414deb1429f3b1/plugins/github-releases.lua"
sha256 = "8f6ba5b69781a7cd1f9a3fc36f82f2ba7448063d13c8817c120ea6144ffb1674"

[plugins]
cmake = { resolver = "github", coordinate = "daukle/cmake@^1.0.0" }

[toolchains.cmake]
version = "4.4"
standard = 17
